exp_name: SSN_gelu_1e-3

# model related
model:
  name: 'SSN'
  in_channels: 1
  out_channels: 1
  resnet: False 

  mid_act: "gelu"
  out_act: 'gelu'

  optimizer: 'Adam'
  weight_decay: 4e-5
  beta1: 0.9


# dataset
dataset:
  name: 'SSN_Dataset'
  hdf5_file: 'Dataset/SSN/ssn_shadow/shadow_base/ssn_base.hdf5'
  shadow_per_epoch: 10


# test_dataset:
#   name: 'SSN_Dataset'
#   hdf5_file: 'Dataset/SSN/ssn_shadow/shadow_base/ssn_base.hdf5'


# training related
hyper_params:
  lr: 1e-3
  epochs: 100000
  workers: 10
  batch_size: 10
  save_epoch: 10

  eval_batch: 10
  eval_save: False

  # visualization
  vis_iter: 100     # iteration for visualization
  save_iter: 100
  n_cols: 5
  gpus:
    - 0

  default_folder: 'weights'
  resume: False
  weight_file: 'latest'
